### ISSUE TITLE
Doesn't download any files

### ISSUE THREAD

**Issue by overkill864** [Azeirah/scrybble#1]
I sign in, it says it sees files, tries to download them, the fails and says "are you signed in"

**Comment by Azeirah** [comment]
Hey, thanks for the report, I'm looking in to it.

What's your username on Scrybble?

**Comment by overkill864** [comment]
You mean my email? Unsure if its not the email, matthias@spellbound.com Thanks!

**Comment by Azeirah** [comment]
> You mean my email? Unsure if its not the email, [matthias@spellbound.com](mailto:matthias@spellbound.com) Thanks! I notice clicking any file in the dashboard just leads to a white page online.

Thanks, I made some updates to the scrybble plugin. Let me know if you're still having issues with version 2.4.0

![afbeelding](https://user-images.githubusercontent.com/4040870/208200814-6d56749f-b015-4faa-a794-3eadae31935f.png)

**Comment by Azeirah** [comment]
Also, synced files end up in a folder called `rm-highlights` in your Obsidian vault. I hadn't made that clear anywhere yet

**Comment by overkill864** [comment]
Awesome! Thank you, it definitly syncs now. But I notice now that I am misunderstanding the point of the plugin then maybe. It synced only a couple docs, so I am assuming its only syncing ‘highlights’. To be frank, I am unsure what a highlight is in remarkable. It doesnt appear to be favorites or any documents using the highlighter pen. What constitutes a highlight?

**Comment by Azeirah** [comment]
You're right, right now it's configured to cut out pages without highlights or notes by default.

I'm going to change the default setting to sync the entire document, and leave the settings it's on now as an option.

In addition to this, I'm 100% it's still straight up crashing for some files. Usually these crashes are really easy to fix, it's mostly just a matter of lacking actual test files that _cause_ the crash...

My plan is to change the default setting to sync full documents tomorrow. In hindsight it makes a lot more sense to do it that way 😅
