### ISSUE TITLE
Synced files do not got into the correct folders

### ISSUE THREAD

**Issue by syloktools** [Azeirah/scrybble#2]
Files do not end up in the correct folders when syncing. 

The created rm-highlights folder in Obsidian is empty and the complete PDFs are pulled down the the root of the vault and named rm-highlightsXXX.

Can we created an option to tell the plugin where we want the synced files to be placed?

**Comment by Azeirah** [comment]
I'll look into it. It would definitely make sense to add an option to configure the folder location so I'll add that when fixing the problem.

What operating system do you use by the way? Are you on Windows?

**Comment by Azeirah** [comment]
I've updated scrybble so that the files are downloaded to `/rm-highlights/your-files-here`

It also creates mirrors subfolders from your ReMarkable, if you download `book-notes/how-to-read-a-book` it will end up in `/rm-highlights/book-notes/how-to-read-a-book.pdf`

**Comment by Azeirah** [comment]
In the most recent release v2.7.0, you can configure where you want your notes to sync to.
