### ISSUE TITLE
synchro not working since obsidian 1.6

### ISSUE THREAD

**Issue by guix54** [Azeirah/scrybble#7]
Hello Azeirah
My synchro is not working since last update from obsidian team (i'm catalyst)

**Comment by Azeirah** [comment]
> Hello Azeirah My synchro is not working since last update from obsidian team (i'm catalyst)

Hey, I just finished performing a migration for the scrybble site to a new host. It looks like this is causing issues for some people. It doesn't have anything to do with the Obsidian update.

Have you logged out and back in again? Authentication has been reset for all accounts.

I'm investigating the issue right now.

**Comment by Azeirah** [comment]
Hi, I think there was an issue with the sync delta token. The database migration caused the token to reset, it "looked" like it was going well for my account but it actually wasn't.

I've updated the sync delta token appropriately, sync should work properly now. Can you confirm it's working well for you now? Thanks :)

**Comment by guix54** [comment]
yes all is ok now fine thanks!
