### ISSUE TITLE
synchro failed

### ISSUE THREAD

**Issue by guix54** [Azeirah/scrybble#8]
Hello Azeirah

I try to transfer some handwritten notes into my vault but all sync are NOK (red in sync status)
Can you see this issue?
thanks

**Comment by Azeirah** [comment]
Can you send the email address you use for scrybble to smg@smgmusicdisplay.com? I'll investigate what's going on

**Comment by guix54** [comment]
Hello Azeirah have you received the email adress (the smg...returns me an error)

**Comment by svbremner** [comment]
Having the same issue

**Comment by Azeirah** [comment]
There was an issue with an incorrect version of (https://github.com/azeirah/remarks) being deployed to the server. Can you confirm new syncs work for you again?

- [ ] @svbremner?
- [ ] @guix54?

I recently moved hosting and I'm still getting used to a new deployment cycle, apologies for the issues it's causing!

**Comment by guix54** [comment]
Seems ok for me
Many thanks

**Comment by guix54** [comment]
hello Azeirah
The sync is ok for the file but synced files are empty.
It's really annoying.
best regards
Guillaume

Le mer. 5 juin 2024 à 20:48, Guillaume Lefevre ***@***.***> a
écrit :

> Seems ok for me
> Many thanks
>

**Comment by guix54** [comment]
hello Azeirah, some news about the sync?

**Comment by Azeirah** [comment]
> hello Azeirah, some news about the sync?

For issues with files, I'll need info about what the files contain. For the best support, I'll need

1. The name of the file
1. Your permission to access the file
2. The file as a PDF, exported by ReMarkable themselves

I understand this is not always possible due to privacy concerns. If it's not possible, it will be a slower process to figure out the exact issue.

**Comment by guix54** [comment]
hello
name test scrybble
my permission of course
[test.pdf](https://github.com/user-attachments/files/15749295/test.pdf)

**Comment by Azeirah** [comment]
> hello name test scrybble my permission of course [test.pdf](https://github.com/user-attachments/files/15749295/test.pdf)

Thank you!

It is very strange that just regular annotations aren't converting properly. I'm looking into it.

**Comment by Azeirah** [comment]
> hello name test scrybble my permission of course [test.pdf](https://github.com/user-attachments/files/15749295/test.pdf)

The issue with the blank file synchronization is fixed. Let me know how it goes for you.

**Comment by guix54** [comment]
Hello Laura, perfect all is ok now thanks
